app:
    resource: "@AppBundle/Controller/"
    type:     annotation

home:
    path:    /home
    defaults: { _controller: AppBundle:Home:home }

user_login:
    path:     /home
    defaults: { _controller: AppBundle:Home:login }

user_login_check:
    path:    /index
    defaults: { _controller: AppBundle:Index:index}

index:
    path:    /index
    defaults: { _controller: AppBundle:Index:index }

user_register:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }

user_register_confirmed:
    path:     /index
    defaults: { _controller: AppBundle:Index:index }

prognostic:
    path:    /prognostic
    defaults: { _controller: AppBundle:Prognostic:prognostic }


# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



